/**
 * Integration test: contentPlugin in non-SSG (SSR) mode.
 *
 * Verifies that the stub file generated by contentPlugin:
 * 1. Uses a relative import.meta.url path (no machine-specific absolute paths)
 * 2. Does NOT register a chokidar watcher (no 'close' hook) in production mode
 *
 * Run with: pnpm --filter @beatzball/litro test
 */

import { describe, it, expect, afterEach } from 'vitest';
import { readFile, rm, mkdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'pathe';
import { tmpdir } from 'node:os';
import contentPlugin from './plugin.js';

/** Creates a minimal project tree in a temp directory and returns rootDir. */
async function makeFixtureProject(): Promise<string> {
  const rootDir = join(tmpdir(), `litro-content-ssr-test-${Date.now()}`);
  const contentDir = join(rootDir, 'content');
  await mkdir(contentDir, { recursive: true });
  // Minimal content file so the plugin doesn't return early.
  await writeFile(
    join(contentDir, 'intro.md'),
    '---\ntitle: Intro\ndate: 2025-01-01\n---\nHello SSR',
    'utf-8',
  );
  // litro.recipe.json pointing to the content dir.
  await writeFile(
    join(rootDir, 'litro.recipe.json'),
    JSON.stringify({ contentDir: 'content' }),
    'utf-8',
  );
  return rootDir;
}

/** Minimal Nitro mock for production mode. */
function makeProdNitro(rootDir: string) {
  const registeredHooks: string[] = [];
  return {
    options: { rootDir, dev: false },
    logger: { info: () => {}, warn: () => {}, error: () => {} },
    hooks: {
      hook(event: string, _handler: unknown) {
        registeredHooks.push(event);
      },
      callHook() {},
    },
    _registeredHooks: registeredHooks,
    _alias: {} as Record<string, string>,
  };
}

describe('contentPlugin in SSR (production) mode', () => {
  const roots: string[] = [];

  afterEach(async () => {
    for (const root of roots) {
      await rm(root, { recursive: true, force: true });
    }
    roots.length = 0;
  });

  it('generates a stub with import.meta.url dev path and absolute fallback', async () => {
    const rootDir = await makeFixtureProject();
    roots.push(rootDir);

    const nitro = makeProdNitro(rootDir);
    await contentPlugin(nitro as Parameters<typeof contentPlugin>[0]);

    const stubPath = join(rootDir, 'server/stubs/litro-content.js');
    expect(existsSync(stubPath)).toBe(true);

    const content = await readFile(stubPath, 'utf-8');

    // Dev path: must use import.meta.url for portable resolution.
    expect(content).toContain('import.meta.url');
    // Production fallback: must embed the absolute content dir path.
    const contentDir = join(rootDir, 'content');
    expect(content).toContain(contentDir);
    // Must use existsSync to pick the correct path at runtime.
    expect(content).toContain('existsSync');
  });

  it('does not register a close hook (no watcher) in production mode', async () => {
    const rootDir = await makeFixtureProject();
    roots.push(rootDir);

    const nitro = makeProdNitro(rootDir);
    await contentPlugin(nitro as Parameters<typeof contentPlugin>[0]);

    expect(nitro._registeredHooks).not.toContain('close');
  });

  it('sets nitro.options.alias for litro:content', async () => {
    const rootDir = await makeFixtureProject();
    roots.push(rootDir);

    const nitro = makeProdNitro(rootDir);
    // Allow alias mutation.
    (nitro.options as Record<string, unknown>).alias = {};
    await contentPlugin(nitro as Parameters<typeof contentPlugin>[0]);

    const alias = (nitro.options as Record<string, unknown>).alias as Record<string, string>;
    expect(alias['litro:content']).toBeDefined();
    expect(alias['litro:content']).toContain('litro-content.js');
  });
});
