/**
 * Nitro build-time plugin: content layer
 *
 * Reads litro.recipe.json to find contentDir, then:
 *   1. Writes a physical stub file at server/stubs/litro-content.js
 *   2. Sets nitro.options.alias['litro:content'] → stub path (for Rollup)
 *   3. Exposes contentDir on nitro.options for other plugins (e.g. SSG)
 *
 * The stub is plain JavaScript (not TypeScript) so jiti can import it
 * and @rollup/plugin-node-resolve can find it as a fallback.
 */

import type { Nitro } from 'nitropack';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve, relative } from 'pathe';
import { resolveContentDir } from './resolve-content-dir.js';

/**
 * Generates the stub JS module content for `litro:content`.
 * Plain JavaScript (no TypeScript syntax) so Rollup and jiti can parse it.
 */
function generateStubContent(relativeContentDir: string, absoluteContentDir: string): string {
  return `// @generated by litro content plugin — do not edit
// litro:content stub — resolves to the project's content directory
import { ContentIndex } from '@beatzball/litro/content';
import { existsSync } from 'node:fs';

// Dev: import.meta.url resolves relative to the stub's original location (correct).
// Production: Rollup inlines this into a chunk at a different path, so import.meta.url
// resolves incorrectly. Fall back to the absolute path embedded at build time.
const _devDir = new URL(${JSON.stringify(relativeContentDir)}, import.meta.url).pathname;
const _contentDir = existsSync(_devDir) ? _devDir : ${JSON.stringify(absoluteContentDir)};
const _index = new ContentIndex(_contentDir);
const _isDev = process.env.LITRO_DEV === 'true';

// Production: start building eagerly at server startup so the first request
// is not blocked. The promise is cached inside ContentIndex.
// Dev: do not pre-build; rebuild lazily on each call so content edits are
// reflected after the browser reloads — no server restart required.
const _ready = _isDev ? null : _index.build().catch((err) => {
  console.error('[litro:content] Failed to build content index:', err);
});

async function _ensureReady() {
  if (_isDev) {
    // Reset the memoized build promise so we always re-scan in dev mode.
    // TypeScript 'private' is a plain JS property at runtime — safe to reset
    // from generated JS.
    _index._buildPromise = null;
    await _index.build();
  } else {
    await _ready;
  }
}

export async function getPosts(options) {
  await _ensureReady();
  return _index.getPosts(options);
}

export async function getPost(slug) {
  await _ensureReady();
  return _index.getPost(slug);
}

export async function getTags() {
  await _ensureReady();
  return _index.getTags();
}

export async function getGlobalData() {
  await _ensureReady();
  return _index.getGlobalData();
}
`;
}

export default async function contentPlugin(nitro: Nitro): Promise<void> {
  const rootDir = nitro.options.rootDir;
  const contentDir = await resolveContentDir(rootDir);

  if (!existsSync(contentDir)) {
    // No content directory — nothing to do
    return;
  }

  // Write stub file so @rollup/plugin-node-resolve and jiti can find it
  const stubDir = resolve(rootDir, 'server', 'stubs');
  const relativeContentDir = './' + relative(stubDir, contentDir);
  const stubContent = generateStubContent(relativeContentDir, contentDir);
  await mkdir(stubDir, { recursive: true });
  const stubPath = join(stubDir, 'litro-content.js');
  await writeFile(stubPath, stubContent, 'utf-8');

  // Alias 'litro:content' → stub path in Rollup (via Nitro's alias option)
  if (!nitro.options.alias) {
    (nitro.options as Record<string, unknown>).alias = {};
  }
  (nitro.options.alias as Record<string, string>)['litro:content'] = stubPath;

  // Store contentDir and stubPath so other plugins (ssg.ts) can read them
  const opts = nitro.options as Record<string, unknown>;
  opts['__litroContentDir'] = contentDir;
  opts['__litroContentStub'] = stubPath;

  nitro.logger.info(`[litro:content] Content directory: ${contentDir}`);
}
