/**
 * Nitro build-time plugin: content layer
 *
 * Reads litro.recipe.json to find contentDir, then:
 *   1. Writes a physical stub file at server/stubs/litro-content.js
 *   2. Sets nitro.options.alias['litro:content'] → stub path (for Rollup)
 *   3. Exposes contentDir on nitro.options for other plugins (e.g. SSG)
 *
 * The stub is plain JavaScript (not TypeScript) so jiti can import it
 * and @rollup/plugin-node-resolve can find it as a fallback.
 */

import type { Nitro } from 'nitropack';
import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'pathe';
import { resolveContentDir } from './resolve-content-dir.js';

/**
 * Generates the stub JS module content for `litro:content`.
 * Plain JavaScript (no TypeScript syntax) so Rollup and jiti can parse it.
 */
function generateStubContent(absoluteContentDir: string): string {
  // Plain JavaScript (no TypeScript syntax) — Rollup and jiti parse it directly.
  // The ContentIndex is created at module eval time and begins building eagerly
  // so the first request finds a warm index rather than waiting for the full build.
  return `// @generated by litro content plugin — do not edit
// litro:content stub — resolves to the project's content directory
import { ContentIndex } from '@beatzball/litro/content';

const _index = new ContentIndex(${JSON.stringify(absoluteContentDir)});

// Start building eagerly at server startup so the first request is not blocked.
// The promise is cached; getPosts/getPost/getTags/getGlobalData await it if
// the eager build has not yet completed.
const _ready = _index.build().catch((err) => {
  console.error('[litro:content] Failed to build content index:', err);
});

export async function getPosts(options) {
  await _ready;
  return _index.getPosts(options);
}

export async function getPost(slug) {
  await _ready;
  return _index.getPost(slug);
}

export async function getTags() {
  await _ready;
  return _index.getTags();
}

export async function getGlobalData() {
  await _ready;
  return _index.getGlobalData();
}
`;
}

export default async function contentPlugin(nitro: Nitro): Promise<void> {
  const rootDir = nitro.options.rootDir;
  const contentDir = await resolveContentDir(rootDir);

  if (!existsSync(contentDir)) {
    // No content directory — nothing to do
    return;
  }

  const stubContent = generateStubContent(contentDir);

  // Write stub file so @rollup/plugin-node-resolve and jiti can find it
  const stubDir = resolve(rootDir, 'server', 'stubs');
  await mkdir(stubDir, { recursive: true });
  const stubPath = join(stubDir, 'litro-content.js');
  await writeFile(stubPath, stubContent, 'utf-8');

  // Alias 'litro:content' → stub path in Rollup (via Nitro's alias option)
  if (!nitro.options.alias) {
    (nitro.options as Record<string, unknown>).alias = {};
  }
  (nitro.options.alias as Record<string, string>)['litro:content'] = stubPath;

  // Store contentDir and stubPath so other plugins (ssg.ts) can read them
  const opts = nitro.options as Record<string, unknown>;
  opts['__litroContentDir'] = contentDir;
  opts['__litroContentStub'] = stubPath;

  nitro.logger.info(`[litro:content] Content directory: ${contentDir}`);

  // Dev mode: re-run on content file changes
  if (nitro.options.dev) {
    nitro.hooks.hook('dev:reload', async () => {
      // Stub content doesn't change; ContentIndex rebuilds lazily on next query
      nitro.logger.info('[litro:content] Dev reload — content index will rebuild on next request');
    });
  }
}
