/**
 * FAST playground client entry point.
 *
 * CRITICAL IMPORT ORDER
 * ─────────────────────
 * @microsoft/fast-element/install-element-hydration.js MUST be the very first
 * import — it installs HydratableElementController so FASTElement respects the
 * defer-hydration attribute emitted by @microsoft/fast-ssr.
 */

// Step 1 — MUST BE FIRST: install FAST hydration support
import '@microsoft/fast-element/install-element-hydration.js';

// Step 2 — client runtime custom elements (router outlet + link)
import '@beatzball/litro/adapter/fast/runtime';

// Step 3 — routes generated by the page scanner
import { routes } from './routes.generated.js';

// Step 4 — initialize the router
const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
if (outlet) {
  outlet.routes = routes;
} else {
  console.warn(
    '[litro] no <litro-outlet> found in the document. ' +
      'Make sure the HTML shell includes <litro-outlet></litro-outlet>.',
  );
}
