import { defineNitroConfig } from 'nitropack/config';
import type { Nitro } from 'nitropack';
import { resolve } from 'node:path';
import { ssrPreset } from '../packages/framework/dist/config/presets.js';
import pagesPlugin from '../packages/framework/dist/plugins/pages.js';
import agentsPlugin from '../packages/litro-agent/dist/plugin.js';

// Tell the adapter resolver to use FAST instead of Lit.
process.env.LITRO_ADAPTER = 'fast';

export default defineNitroConfig({
  ...ssrPreset(),

  srcDir: 'server',

  publicAssets: [
    {
      dir: '../dist/client',
      baseURL: '/_litro/',
      maxAge: 31536000,
    },
    {
      dir: '../public',
      baseURL: '/',
      maxAge: 0,
    },
  ],

  // FAST Element uses decorators (@attr, @observable) that need esbuild config.
  esbuild: {
    options: {
      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true,
          useDefineForClassFields: false,
        },
      },
    },
  },

  ignore: ['**/middleware/vite-dev.ts'],
  handlers: [
    {
      middleware: true,
      handler: resolve('./server/middleware/vite-dev.ts'),
      env: 'dev',
    },
    {
      // Agent session RPC endpoint (POST starts/continues a turn, GET
      // replays/live-tails it). Same timing trap as the page manifest: the
      // handler stub is generated by the litro agents plugin (build:before)
      // before rollup compiles it, but the route must be declared statically
      // here because the dev server reads handler config before that fires.
      route: '/__litro/agent/:agent/:session',
      method: 'post',
      handler: resolve('./server/stubs/agent-handler.ts'),
    },
    {
      route: '/__litro/agent/:agent/:session',
      method: 'get',
      handler: resolve('./server/stubs/agent-handler.ts'),
    },
  ],

  hooks: {
    'build:before': async (nitro: Nitro) => {
      // Run page scanner — scans pages/, writes manifest stub, sets virtual module
      await pagesPlugin(nitro);
      // Run agent scanner — scans agents/*/agent.ts, writes manifest +
      // config + handler stubs (the routes are declared in handlers above)
      await agentsPlugin(nitro);
    },
  },

  compatibilityDate: '2026-02-28',

  routeRules: {
    '/__litro/agent/**': {
      headers: { 'cache-control': 'no-store' },
    },
    '/_litro/**': {
      headers: { 'cache-control': 'public, max-age=31536000, immutable' },
    },
  },
});
