/**
 * Nitro build-time plugin: server-action scanner and endpoint registrar.
 *
 * Called directly from nitro.config.ts hooks['build:before'], exactly like
 * the page scanner (see pages.ts — this file deliberately mirrors it). It:
 *
 *   1. Scans `**\/*.server.{ts,tsx,js,mjs}` under rootDir
 *   2. Generates the `#litro/action-manifest` virtual module (absolute-path
 *      imports for Rollup) and the physical stub
 *      `server/stubs/action-manifest.ts` (relative .js imports for tsc and
 *      @rollup/plugin-node-resolve via package.json "imports")
 *   3. Generates `server/stubs/action-handler.ts` — a one-line handler that
 *      feeds the manifest into createActionHandler()
 *   4. Registers POST /__litro/action/:id on nitro.options.handlers pointing
 *      at that generated stub (no consumer-owned route file)
 *
 * The manifest intentionally has NO export-name information: the handler
 * enumerates each module's exports at runtime (Object.keys) and hashes
 * (relPath, exportName) pairs itself — so this plugin never parses
 * TypeScript.
 *
 * Consumer wiring (four one-time edits, see playground):
 *   - nitro.config.ts:   await actionsPlugin(nitro) in hooks['build:before']
 *   - nitro.config.ts:   handlers entry for POST /__litro/action/:id -> ./server/stubs/action-handler.ts
 *   - package.json:      "imports": { "#litro/action-manifest": "./server/stubs/action-manifest.ts" }
 *   - vite.config.ts:    litroActionsPlugin() from '@beatzball/litro/vite'
 */
import type { Nitro } from 'nitropack';
import fastGlob from 'fast-glob';
import { resolve, join, relative } from 'pathe';
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { normalizeActionPath } from '../actions/hash.js';

const MANIFEST_STUB_REL = join('server', 'stubs', 'action-manifest.ts');
const HANDLER_STUB_REL = join('server', 'stubs', 'action-handler.ts');

async function scanActionFiles(rootDir: string): Promise<string[]> {
  const files = await fastGlob('**/*.server.{ts,tsx,js,mjs}', {
    cwd: rootDir,
    absolute: true,
    onlyFiles: true,
    followSymbolicLinks: true,
    ignore: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.output/**',
      '**/.nitro/**',
      '**/server/stubs/**',
      '**/*.d.ts',
      '**/*.test.*',
      '**/*.spec.*',
    ],
  });
  return files.sort();
}

/** Same convention as pages.ts: relative specifier with a .js extension,
 *  computed from the directory containing the generated file. */
function toRelativeImportSpecifier(fromFile: string, toFile: string): string {
  const rel = relative(join(fromFile, '..'), toFile).replace(/\.(ts|tsx|mjs)$/, '.js');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function generateActionManifest(
  files: string[],
  rootDir: string,
  variant: 'virtual' | 'stub',
): string {
  const stubPath = join(rootDir, MANIFEST_STUB_REL);
  const importSpecifier = (f: string): string =>
    variant === 'virtual' ? f : toRelativeImportSpecifier(stubPath, f);

  const imports = files
    .map((f, i) => `import * as _action${i} from ${JSON.stringify(importSpecifier(f))};`)
    .join('\n');

  const entries = files
    .map(
      (f, i) =>
        `  { relPath: ${JSON.stringify(normalizeActionPath(rootDir, f))}, module: _action${i} }`,
    )
    .join(',\n');

  return `// @ts-nocheck
// @generated by litro action scanner — do not edit
// This is the #litro/action-manifest virtual module.
// It is re-generated on every build and dev-reload.
${imports}

export const actionModules = [
${entries}
];
`;
}

const HANDLER_STUB_SOURCE = `// @ts-nocheck
// @generated by litro action scanner — do not edit
// Runtime handler for POST /__litro/action/:id — registered automatically by
// the litro actions plugin (nitro.options.handlers).
import { createActionHandler } from '@beatzball/litro/actions/handler';
import { actionModules } from '#litro/action-manifest';

export default createActionHandler(actionModules);
`;

async function writeStub(rootDir: string, relPath: string, content: string): Promise<void> {
  const abs = resolve(rootDir, relPath);
  await mkdir(join(abs, '..'), { recursive: true });
  // Skip identical writes: server/stubs/ sits inside Nitro's watched srcDir,
  // so an unconditional write on every dev:reload re-triggers the watcher and
  // the dev server reload-loops forever.
  try {
    const existing = await readFile(abs, 'utf-8');
    if (existing === content) return;
  } catch {
    // File does not exist yet — fall through to write.
  }
  await writeFile(abs, content, 'utf-8');
}

export default async function actionsPlugin(nitro: Nitro): Promise<void> {
  async function runScan(): Promise<void> {
    const rootDir = nitro.options.rootDir;
    const files = await scanActionFiles(rootDir);

    nitro.options.virtual['#litro/action-manifest'] = generateActionManifest(
      files,
      rootDir,
      'virtual',
    );
    await writeStub(rootDir, MANIFEST_STUB_REL, generateActionManifest(files, rootDir, 'stub'));
    await writeStub(rootDir, HANDLER_STUB_REL, HANDLER_STUB_SOURCE);

    if (files.length > 0) {
      nitro.logger.info(
        `[litro] Registered ${files.length} action module${files.length === 1 ? '' : 's'}`,
      );
    }
  }

  await runScan();

  // NOTE: the endpoint route is NOT registered here. Pushing into
  // nitro.options.handlers at build:before is too late for the dev server
  // (it reads handler config before this hook fires — verified empirically;
  // same timing trap documented for devHandlers in vite-dev.ts). Consumers
  // declare the route statically in nitro.config.ts instead:
  //
  //   handlers: [{
  //     route: '/__litro/action/:id',
  //     method: 'post',
  //     handler: resolve('./server/stubs/action-handler.ts'),
  //   }],
  //
  // This plugin guarantees that stub file exists before rollup compiles it.

  nitro.hooks.hook('dev:reload', async () => {
    await runScan();
  });
}
