/**
 * Nitro build-time plugin: page scanner and route generator
 *
 * This is a Nitro BUILD-TIME plugin (registered in nitro.config.ts under `plugins`).
 * It runs during `nitro:build:before` (and on dev reload) to:
 *
 *   1. Scan `pages/**\/*.{ts,tsx}` relative to the project root
 *   2. Convert each file path to a LitroRoute (via path-to-route utilities)
 *   3. Generate the `#litro/page-manifest` virtual module — consumed at runtime
 *      by the catch-all Nitro handler (server/routes/[...].ts)
 *   4. Write `dist/client/routes.generated.ts` — consumed at build time by the
 *      @vaadin/router client bootstrap
 *   5. Push all non-dynamic routes into `nitro.options.prerender.routes` for
 *      static site generation support
 *
 * Virtual module strategy (from R-4 research):
 *   nitro.options.virtual['#litro/page-manifest'] is set to the generated
 *   module source string. Nitro handles the rest — the key is available as an
 *   importable module ID from any server-side file.
 *
 * Important: DO NOT register individual Nitro handlers per page.
 * The single catch-all handler in server/routes/[...].ts is the correct
 * pattern — it reads the manifest and dispatches to the right component.
 */

import type { Nitro } from 'nitropack';
import fastGlob from 'fast-glob';
import { resolve, join } from 'pathe';
import { writeFile, mkdir } from 'node:fs/promises';
import { fileToRoute, compareRoutes } from './path-to-route.js';
import type { LitroRoute } from '../types/route.js';

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Scans `pages/` under the given root directory and returns all page files
 * as absolute paths, sorted lexicographically.
 */
async function scanPageFiles(rootDir: string): Promise<string[]> {
  const pagesDir = resolve(rootDir, 'pages');

  const files = await fastGlob('**/*.{ts,tsx}', {
    cwd: pagesDir,
    absolute: true,
    followSymbolicLinks: true,
    onlyFiles: true,
    ignore: [
      '**/*.d.ts',     // TypeScript declaration files — never page routes
      '**/*.test.ts',  // Test files
      '**/*.spec.ts',  // Spec files
      '**/-*.ts',      // Dash-prefixed files are disabled routes
      '**/-*.tsx',
    ],
  });

  return files.sort();
}

/**
 * Generates the TypeScript source for the `#litro/page-manifest` virtual module.
 *
 * The generated module exports a `routes` array of LitroRoute objects that
 * the catch-all Nitro handler imports at runtime to decide which component to render.
 */
function generateManifestModule(routes: LitroRoute[], pageFiles: string[]): string {
  const routesJson = JSON.stringify(routes, null, 2);

  // Static imports of every page module.
  // These are processed by Rollup's TypeScript/esbuild plugin at build time —
  // the TypeScript is compiled and bundled as side effects. This registers all
  // @customElement decorators (calls customElements.define()) so that
  // @lit-labs/ssr can find the component definitions at render time.
  // No runtime dynamic import of .ts files is needed.
  const imports = pageFiles
    .map((f, i) => `import * as _page${i} from ${JSON.stringify(f)};`)
    .join('\n');

  // Registry mapping filePath → bundled module object.
  // Consumed by createPageHandler() via the catch-all route to access
  // pageData exports without a separate runtime dynamic import.
  const registryEntries = pageFiles
    .map((f, i) => `  ${JSON.stringify(f)}: _page${i}`)
    .join(',\n');

  // NOTE: This must be valid JavaScript (no TypeScript syntax) because it is
  // fed directly to Rollup as a virtual module source. TypeScript-specific
  // syntax (e.g. `import type`) would cause a parse error at bundle time.
  // The static imports above ARE TypeScript files but Rollup's esbuild plugin
  // compiles them — the virtual module source itself is plain JS.
  return `// @generated by litro page scanner — do not edit
// This is the #litro/page-manifest virtual module.
// It is re-generated on every build and dev-reload.
${imports}

export const routes = ${routesJson};

// Module registry — maps filePath strings to bundled module objects.
// Allows the catch-all handler to access pageData without a .ts runtime import.
export const pageModules = {
${registryEntries}
};

// Default export for backward compatibility with: import pages from '#litro/page-manifest'
export default routes;
`;
}

/**
 * Generates the `dist/client/routes.generated.ts` file for @vaadin/router.
 *
 * Each route entry uses an async `action()` callback to dynamically import
 * the page module, and sets `component` to the custom element tag name.
 *
 * @vaadin/router's Route shape:
 *   { path: string, action?: Function, component?: string }
 */
function generateClientRoutes(routes: LitroRoute[], rootDir: string): string {
  const routeLines = routes
    .map(route => {
      // Convert absolute filePath to a root-relative import path for the client.
      // The client imports pages relative to the project root (served by Vite).
      const relPath = route.filePath
        .replace(rootDir, '')
        .replace(/\.tsx?$/, '.js');

      // Ensure the path starts with /
      const importPath = relPath.startsWith('/') ? relPath : `/${relPath}`;

      return [
        `  {`,
        `    path: ${JSON.stringify(route.path)},`,
        `    action: async () => { await import(${JSON.stringify(importPath)}); },`,
        `    component: ${JSON.stringify(route.componentTag)},`,
        `  },`,
      ].join('\n');
    })
    .join('\n');

  return `// @generated by litro page scanner — do not edit
// This file is consumed by the @vaadin/router client bootstrap (app.ts).
// Re-generated on every build.

import type { Route } from '@vaadin/router';

export const routes: Route[] = [
${routeLines}
];
`;
}

/**
 * Writes the client routes file to <rootDir>/routes.generated.ts.
 *
 * The file lives at the project root (not in dist/) so it:
 *   1. Is not deleted by Vite's `emptyOutDir` during production builds
 *   2. Can be imported by app.ts as a source file (Vite transforms it)
 *   3. Is freshly regenerated before every `vite build` via the CLI pre-scan step
 */
async function writeClientRoutes(rootDir: string, content: string): Promise<void> {
  const outPath = join(rootDir, 'routes.generated.ts');
  await writeFile(outPath, content, 'utf-8');
}

/**
 * Standalone scanner: scans pages/, generates the client routes file.
 *
 * Exported so the CLI can call it before `vite build` to ensure fresh routes
 * are baked into the client bundle. Also called by the Nitro `build:before`
 * hook (via pagesPlugin) for the server-side manifest.
 */
export async function scanAndWriteClientRoutes(rootDir: string): Promise<void> {
  const pagesDir = resolve(rootDir, 'pages');
  let pageFiles: string[];
  try {
    pageFiles = await scanPageFiles(rootDir);
  } catch {
    return; // pages/ doesn't exist yet — silently skip
  }
  if (pageFiles.length === 0) return;

  const routes = pageFiles
    .map(file => fileToRoute(file, pagesDir))
    .sort(compareRoutes);

  const content = generateClientRoutes(routes, rootDir);
  await writeClientRoutes(rootDir, content);
}

/**
 * Writes the server-side page manifest to the physical stub file.
 *
 * This overrides the fallback stub so that @rollup/plugin-node-resolve (which
 * intercepts '#' imports via package.json "imports" before Nitro's virtual
 * module plugin runs) resolves the real generated routes instead of the empty
 * stub.
 *
 * The stub file path is `server/stubs/page-manifest.ts` relative to rootDir —
 * the same path that playground/package.json "imports" points to.
 */
async function writeServerManifest(rootDir: string, content: string): Promise<void> {
  const stubDir = resolve(rootDir, 'server', 'stubs');
  await mkdir(stubDir, { recursive: true });
  const stubPath = join(stubDir, 'page-manifest.ts');
  await writeFile(stubPath, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// Server-side stub for @vaadin/router
// ---------------------------------------------------------------------------

/**
 * Returns a Rollup plugin that intercepts `@vaadin/router` imports in the
 * **server** bundle and replaces them with a no-op stub.
 *
 * Why: The `litro/runtime` barrel re-exports `LitroOutlet` and `LitroLink`,
 * both of which import `@vaadin/router` at the top level. `@vaadin/router`
 * transitively loads `@vaadin/vaadin-development-mode-detector`, which reads
 * `window` at module evaluation time — crashing Node.js.
 *
 * The stub satisfies the interface used by `LitroOutlet` and `LitroLink`
 * without any DOM/window access. Since those components are never rendered
 * server-side, the stub is never actually invoked at runtime.
 *
 * Note: This plugin is added to Nitro's rollup config (server bundle only).
 * Vite (client bundle) is unaffected — it bundles the real @vaadin/router.
 */
/** Minimal Rollup plugin interface (avoids a direct 'rollup' type dependency). */
interface MinimalRollupPlugin {
  name: string;
  resolveId(id: string): string | null;
  load(id: string): string | null;
}

function vaadinRouterStubPlugin(): MinimalRollupPlugin {
  const STUB_ID = '\0@vaadin/router-server-stub';
  return {
    name: 'litro:vaadin-router-stub',
    resolveId(id: string) {
      if (id === '@vaadin/router') return STUB_ID;
      return null;
    },
    load(id: string) {
      if (id !== STUB_ID) return null;
      // Minimal stub: satisfies the Router usage in LitroOutlet and LitroLink.
      // - new Router(outlet) — constructor
      // - router.setRoutes(routes) — instance method
      // - Router.go(path) — static method used by LitroLink
      return `
export class Router {
  constructor(_outlet) {}
  setRoutes(_routes) {}
  static go(_path) {}
}
export default Router;
`;
    },
  };
}

/**
 * Prepends the @vaadin/router stub plugin to Nitro's rollup plugin list.
 * Must be called before rollup starts (i.e., from build:before).
 */
function injectVaadinRouterStub(nitro: Nitro): void {
  // nitro.options.rollupConfig may be undefined if the user hasn't set it
  if (!nitro.options.rollupConfig) {
    (nitro.options as Record<string, unknown>).rollupConfig = {};
  }
  const rc = nitro.options.rollupConfig as Record<string, unknown>;
  if (!rc.plugins || !Array.isArray(rc.plugins)) {
    rc.plugins = [];
  }
  // Prepend so it runs before @rollup/plugin-node-resolve
  (rc.plugins as MinimalRollupPlugin[]).unshift(vaadinRouterStubPlugin());
}

// ---------------------------------------------------------------------------
// Main plugin export
// ---------------------------------------------------------------------------

/**
 * The Litro page scanner plugin.
 *
 * Registered as a Nitro build-time plugin via `plugins` in nitro.config.ts:
 *
 *   import pagesPlugin from './plugins/pages';
 *   // or from 'litro/plugins' once the package is built
 *
 *   export default defineNitroConfig({
 *     plugins: ['./plugins/vite-dev.ts', pagesPlugin],
 *   });
 */
/**
 * The Litro page scanner plugin.
 *
 * Called directly from nitro.config.ts hooks['build:before'] so the scan
 * runs before rollup starts. This function:
 *   1. Runs the page scan immediately
 *   2. Registers a dev:reload hook for subsequent hot-reloads
 *
 * Note on Nitro 2.x hook names:
 *   Nitro 2.10 uses 'build:before' (not 'nitro:build:before') and 'dev:reload'
 *   (not 'nitro:dev:reload'). The hooks field in nitro.config.ts is registered
 *   before build:before fires, so plugins must be called directly from
 *   hooks['build:before'] rather than registering nested hooks.
 */
export default async function pagesPlugin(nitro: Nitro): Promise<void> {
  // Stub @vaadin/router in the server bundle to prevent window-access at eval time.
  // Must be done before rollup starts — we're inside build:before so it's safe.
  injectVaadinRouterStub(nitro);

  // ---------------------------------------------------------------------------
  // Core scan function — called both at build time and on dev reload
  // ---------------------------------------------------------------------------
  async function runScan(): Promise<void> {
    const rootDir = nitro.options.rootDir;
    const pagesDir = resolve(rootDir, 'pages');

    // 1. Scan page files
    let pageFiles: string[];
    try {
      pageFiles = await scanPageFiles(rootDir);
    } catch {
      // pages/ directory may not exist yet in a brand-new project — that's fine
      nitro.logger.info('[litro] No pages/ directory found; skipping page scan.');
      return;
    }

    if (pageFiles.length === 0) {
      nitro.logger.info('[litro] No page files found in pages/.');
      const emptyModule = generateManifestModule([], []);
      nitro.options.virtual['#litro/page-manifest'] = emptyModule;
      await writeServerManifest(rootDir, emptyModule);
      return;
    }

    // 2. Convert file paths to route definitions.
    // pagesDir is passed to fileToRoute() so it can strip the prefix when
    // computing relative route paths and component tag names.
    const routes = pageFiles
      .map(file => fileToRoute(file, pagesDir))
      .sort(compareRoutes);

    nitro.logger.info(
      `[litro] Scanned ${routes.length} page${routes.length === 1 ? '' : 's'}: ${routes
        .map(r => r.path)
        .join(', ')}`
    );

    // pageFiles is passed alongside routes so generateManifestModule can emit
    // static imports. The order matches so pageFiles[i] → routes[i].filePath
    // (both are sorted).
    const manifestContent = generateManifestModule(routes, pageFiles);

    // 3a. Set the virtual module — used by Vite's dev resolver.
    nitro.options.virtual['#litro/page-manifest'] = manifestContent;

    // 3b. Write the physical stub file — used by @rollup/plugin-node-resolve in
    //     production builds (it intercepts '#' imports via package.json imports
    //     before Nitro's virtual module plugin can handle them).
    await writeServerManifest(rootDir, manifestContent);

    // 4. Write dist/client/routes.generated.ts for @vaadin/router
    try {
      const clientContent = generateClientRoutes(routes, rootDir);
      await writeClientRoutes(rootDir, clientContent);
      nitro.logger.info('[litro] Wrote routes.generated.ts');
    } catch (err) {
      // Non-fatal: the client routes file is a build artifact consumed by Vite.
      // If Vite hasn't run yet there's no dist/client/ — that's okay in dev.
      nitro.logger.warn(
        `[litro] Could not write dist/client/routes.generated.ts: ${(err as Error).message}`
      );
    }

    // 5. Add all static (non-dynamic, non-catch-all) routes to prerender.routes.
    //    Dynamic routes require explicit listing via the page's generateRoutes()
    //    export — that is handled by the SSG plugin.
    const staticRoutes = routes
      .filter(r => !r.isDynamic && !r.isCatchAll)
      .map(r => r.path);

    if (staticRoutes.length > 0) {
      const existing = nitro.options.prerender?.routes ?? [];
      // Deduplicate — other plugins (or config) may have already added some routes
      const merged = Array.from(new Set([...existing, ...staticRoutes]));
      if (!nitro.options.prerender) {
        (nitro.options as any).prerender = {};
      }
      nitro.options.prerender.routes = merged;
    }
  }

  // Run the scan immediately — this function is called from build:before, so
  // the manifest will be ready before rollup processes the server routes.
  await runScan();

  // Re-scan on dev file changes (Nitro 2.x hook name: 'dev:reload').
  nitro.hooks.hook('dev:reload', async () => {
    nitro.logger.info('[litro] Dev reload — rescanning pages...');
    await runScan();
  });
}
