/**
 * Elena playground client entry point.
 *
 * NO HYDRATION SUPPORT SCRIPT NEEDED
 * ───────────────────────────────────
 * Elena uses progressive enhancement — components upgrade in place when
 * JavaScript loads. No prototype patching or hydration controller required.
 * This is the simplest client entry of all three adapters.
 */

// Client runtime custom elements (router outlet + link)
import '@beatzball/litro/adapter/elena/runtime';

// Routes generated by the page scanner
import { routes } from './routes.generated.js';

// Initialize the router
const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
if (outlet) {
  outlet.routes = routes;
} else {
  console.warn(
    '[litro] no <litro-outlet> found in the document. ' +
      'Make sure the HTML shell includes <litro-outlet></litro-outlet>.',
  );
}
