import { defineNitroConfig } from 'nitropack/config';
import type { Nitro } from 'nitropack';
import { resolve } from 'node:path';
import { ssrPreset } from '../packages/framework/dist/config/presets.js';
import pagesPlugin from '../packages/framework/dist/plugins/pages.js';
import actionsPlugin from '../packages/framework/dist/plugins/actions.js';

// Tell the adapter resolver to use Elena instead of Lit.
process.env.LITRO_ADAPTER = 'elena';

export default defineNitroConfig({
  ...ssrPreset(),

  srcDir: 'server',

  publicAssets: [
    {
      dir: '../dist/client',
      baseURL: '/_litro/',
      maxAge: 31536000,
    },
    {
      dir: '../public',
      baseURL: '/',
      maxAge: 0,
    },
  ],

  // Elena does not use legacy decorators — no special esbuild config needed.

  ignore: ['**/middleware/vite-dev.ts'],
  handlers: [
    {
      middleware: true,
      handler: resolve('./server/middleware/vite-dev.ts'),
      env: 'dev',
    },
    {
      // Server actions RPC endpoint. The handler stub is generated by the
      // litro actions plugin (build:before) before rollup compiles it; the
      // route itself must be declared statically because the dev server
      // reads handler config before build:before fires.
      route: '/__litro/action/:id',
      method: 'post',
      handler: resolve('./server/stubs/action-handler.ts'),
    },
  ],

  hooks: {
    'build:before': async (nitro: Nitro) => {
      // HTMLElement + customElements shim must exist before page modules
      // are imported by the page scanner (jiti evaluates them at build time).
      await import('../packages/framework/dist/adapter/elena/ssr-shim.js');
      await pagesPlugin(nitro);
      // Run action scanner — scans **/*.server.ts, writes manifest + handler
      // stubs (the POST /__litro/action/:id route is declared in handlers above)
      await actionsPlugin(nitro);
    },
  },

  compatibilityDate: '2026-04-09',

  routeRules: {
    // Action RPC endpoint (lives OUTSIDE /_litro/ — that prefix is owned by
    // static assets, whose serve-placeholder middleware would intercept it).
    '/__litro/action/**': {
      headers: { 'cache-control': 'no-store' },
    },
    '/_litro/**': {
      headers: { 'cache-control': 'public, max-age=31536000, immutable' },
    },
  },
});
