packages:
  - 'packages/*'
  - 'playground'
  - 'playground-11ty'
  - 'playground-fast'
  - 'playground-starlight'
  - 'playground-elena'
  - 'playground-starlight-fast'
  - 'docs'
  - 'docs-ssr'
  - 'benchmarks'
  - 'benchmarks/apps/litro'
