// @ts-nocheck
// @generated by litro action scanner — do not edit
// Auto-loaded by Nitro at startup (server/plugins/). Stamps every scanned
// action export with its wire id so actionUrl() works during SSR.
import { stampActionIds } from '@beatzball/litro/actions/server';
import { actionModules } from '#litro/action-manifest';

export default function litroActionsStampPlugin() {
  stampActionIds(actionModules);
}
