// CRITICAL: must be first — patches FASTElement for hydration before any component is loaded.
import '@microsoft/fast-element/install-element-hydration.js';

// Client runtime: FAST adapter router outlet and link custom elements.
import '@beatzball/litro/adapter/fast/runtime';

// Shoelace components (tree-shaken — only what the template uses)
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/icon/icon.js';
import '@shoelace-style/shoelace/dist/components/badge/badge.js';
import '@shoelace-style/shoelace/dist/components/copy-button/copy-button.js';
import '@shoelace-style/shoelace/dist/components/details/details.js';
import '@shoelace-style/shoelace/dist/components/tab-group/tab-group.js';
import '@shoelace-style/shoelace/dist/components/tab/tab.js';
import '@shoelace-style/shoelace/dist/components/tab-panel/tab-panel.js';
import { setBasePath } from '@shoelace-style/shoelace/dist/utilities/base-path.js';

// Point Shoelace's icon loader at the served assets directory
setBasePath('/shoelace/');

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
if (outlet) {
  outlet.routes = routes;
} else {
  console.warn('[litro] <litro-outlet> not found — router will not start.');
}
