// @generated by litro page scanner — do not edit
// This stub is overwritten on every build. It exists so the #litro/page-manifest
// import in server/routes/[...].ts resolves even before the first build.

export const routes: never[] = [];
export const pageModules: Record<string, unknown> = {};
export default routes;
