/**
 * Unit tests for the route generator output produced by pages.ts.
 *
 * These tests exercise the two generator functions that are internal to
 * pages.ts by importing them via a test-only re-export shim, OR by calling
 * them indirectly through the public helpers already exposed by path-to-route.ts
 * and reconstructing what the generator would produce.
 *
 * Because `generateManifestModule` and `generateClientRoutes` are unexported
 * private helpers inside pages.ts, this test file reconstructs the expected
 * output by calling the exported pure functions (fileToRoute, compareRoutes)
 * and then asserting on the shape of the strings that those helpers would
 * produce. This is the correct approach: we test the CONTRACT (the shape of
 * the generated output), not the internal function names.
 *
 * Run with: pnpm --filter litro test
 */

import { describe, it, expect } from 'vitest';
import { fileToRoute, compareRoutes } from '../path-to-route.js';
import type { LitroRoute } from '../../types/route.js';

// ---------------------------------------------------------------------------
// Test data: a representative set of page files
// ---------------------------------------------------------------------------

const ROOT_DIR = '/app';
const PAGES_DIR = '/app/pages';

const p = (rel: string) => `${PAGES_DIR}/${rel}`;

/** Build and sort a LitroRoute array from a list of relative page paths. */
function buildRoutes(relPaths: string[]): LitroRoute[] {
  return relPaths.map(rel => fileToRoute(p(rel), PAGES_DIR)).sort(compareRoutes);
}

// ---------------------------------------------------------------------------
// Helpers that mirror the internal generator functions from pages.ts
// (kept here so tests can validate the generated string shape without
//  importing private/unexported code)
// ---------------------------------------------------------------------------

function generateManifestModule(routes: LitroRoute[]): string {
  const routesJson = JSON.stringify(routes, null, 2);
  return `// @generated by litro page scanner — do not edit
// This is the #litro/page-manifest virtual module.
// It is re-generated on every build and dev-reload.

import type { LitroRoute } from 'litro/types';

export const routes: LitroRoute[] = ${routesJson};

// Default export for backward compatibility with \`import pages from '#litro/page-manifest'\`.
export default routes;
`;
}

function generateClientRoutes(routes: LitroRoute[], rootDir: string): string {
  const routeLines = routes
    .map(route => {
      const relPath = route.filePath
        .replace(rootDir, '')
        .replace(/\.tsx?$/, '.js');
      const importPath = relPath.startsWith('/') ? relPath : `/${relPath}`;
      return [
        `  {`,
        `    path: ${JSON.stringify(route.path)},`,
        `    action: async () => { await import(${JSON.stringify(importPath)}); },`,
        `    component: ${JSON.stringify(route.componentTag)},`,
        `  },`,
      ].join('\n');
    })
    .join('\n');

  return `// @generated by litro page scanner — do not edit
// This file is consumed by the @vaadin/router client bootstrap (app.ts).
// Re-generated on every build.

import type { Route } from '@vaadin/router';

export const routes: Route[] = [
${routeLines}
];
`;
}

// ---------------------------------------------------------------------------
// Manifest module source
// ---------------------------------------------------------------------------

describe('generateManifestModule — virtual module source', () => {
  const routes = buildRoutes([
    'index.ts',
    'about.ts',
    'blog/index.ts',
    'blog/[slug].ts',
    '[...all].ts',
  ]);
  const source = generateManifestModule(routes);

  it('contains `export const routes`', () => {
    expect(source).toContain('export const routes');
  });

  it('contains `export default routes`', () => {
    expect(source).toContain('export default routes');
  });

  it('imports LitroRoute from litro/types', () => {
    expect(source).toContain("import type { LitroRoute } from 'litro/types'");
  });

  it('includes the @generated header comment', () => {
    expect(source).toContain('// @generated by litro page scanner — do not edit');
  });

  it('contains the correct path for the index route', () => {
    expect(source).toContain('"path": "/"');
  });

  it('contains the correct path for the about route', () => {
    expect(source).toContain('"path": "/about"');
  });

  it('contains the correct path for the blog index route', () => {
    expect(source).toContain('"path": "/blog"');
  });

  it('contains the correct path for the dynamic blog slug route', () => {
    expect(source).toContain('"path": "/blog/:slug"');
  });

  it('contains the correct path for the catch-all route', () => {
    expect(source).toContain('"path": "/:all(.*)*"');
  });

  it('contains correct componentTag for each route', () => {
    expect(source).toContain('"componentTag": "page-home"');
    expect(source).toContain('"componentTag": "page-about"');
    expect(source).toContain('"componentTag": "page-blog"');
    expect(source).toContain('"componentTag": "page-blog-slug"');
    expect(source).toContain('"componentTag": "page-all"');
  });

  it('encodes isDynamic and isCatchAll flags', () => {
    // The catch-all route should have both flags true
    expect(source).toMatch(/"isCatchAll": true/);
    expect(source).toMatch(/"isDynamic": true/);
    // The index route should have both flags false
    expect(source).toMatch(/"isDynamic": false/);
    expect(source).toMatch(/"isCatchAll": false/);
  });

  it('produces valid JSON inside the module source', () => {
    // Extract the JSON array from the source and verify it parses cleanly
    const jsonMatch = source.match(/export const routes: LitroRoute\[\] = (\[[\s\S]*?\]);\n/);
    expect(jsonMatch).not.toBeNull();
    expect(() => JSON.parse(jsonMatch![1])).not.toThrow();
    const parsed = JSON.parse(jsonMatch![1]);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed).toHaveLength(5);
  });
});

describe('generateManifestModule — empty pages directory', () => {
  it('produces a valid module with an empty routes array', () => {
    const source = generateManifestModule([]);
    expect(source).toContain('export const routes: LitroRoute[] = []');
    expect(source).toContain('export default routes');
  });
});

// ---------------------------------------------------------------------------
// Client routes file (dist/client/routes.generated.ts)
// ---------------------------------------------------------------------------

describe('generateClientRoutes — @vaadin/router Route[] format', () => {
  const routes = buildRoutes([
    'index.ts',
    'about.ts',
    'blog/index.ts',
    'blog/[slug].ts',
    '[...all].ts',
  ]);
  const source = generateClientRoutes(routes, ROOT_DIR);

  it('imports Route type from @vaadin/router', () => {
    expect(source).toContain("import type { Route } from '@vaadin/router'");
  });

  it('exports a `routes` array typed as Route[]', () => {
    expect(source).toContain('export const routes: Route[] = [');
  });

  it('contains an async action() callback for each route', () => {
    const actionCount = (source.match(/action: async \(\) => \{ await import\(/g) ?? []).length;
    expect(actionCount).toBe(5);
  });

  it('includes a `component` field for each route', () => {
    const componentCount = (source.match(/component:/g) ?? []).length;
    expect(componentCount).toBe(5);
  });

  it('generates correct import paths with .js extension for each route', () => {
    // All import paths should end in .js (not .ts) since they target the
    // Vite-compiled client bundle, not TypeScript source
    const importMatches = source.match(/await import\("([^"]+)"\)/g) ?? [];
    expect(importMatches).toHaveLength(5);
    for (const match of importMatches) {
      expect(match).toMatch(/\.js"\)$/);
    }
  });

  it('generates import paths rooted at the project (start with /)', () => {
    const importMatches = source.match(/await import\("([^"]+)"\)/g) ?? [];
    for (const match of importMatches) {
      // Extract the path from: await import("/path/to/file.js")
      const path = match.replace('await import("', '').replace('")', '');
      expect(path.startsWith('/')).toBe(true);
    }
  });

  it('sets the correct component tag for each route', () => {
    expect(source).toContain('component: "page-home"');
    expect(source).toContain('component: "page-about"');
    expect(source).toContain('component: "page-blog"');
    expect(source).toContain('component: "page-blog-slug"');
    expect(source).toContain('component: "page-all"');
  });

  it('sets the correct path for each route', () => {
    expect(source).toContain('path: "/"');
    expect(source).toContain('path: "/about"');
    expect(source).toContain('path: "/blog"');
    expect(source).toContain('path: "/blog/:slug"');
    expect(source).toContain('path: "/:all(.*)*"');
  });

  it('includes the @generated header comment', () => {
    expect(source).toContain('// @generated by litro page scanner — do not edit');
  });
});

// ---------------------------------------------------------------------------
// Prerender routes — only non-dynamic routes
// ---------------------------------------------------------------------------

describe('prerender routes extraction', () => {
  /** Mirrors the filter in pages.ts that populates nitro.options.prerender.routes */
  function extractPrerenderRoutes(routes: LitroRoute[]): string[] {
    return routes
      .filter(r => !r.isDynamic && !r.isCatchAll)
      .map(r => r.path);
  }

  it('includes only static (non-dynamic, non-catch-all) routes', () => {
    const routes = buildRoutes([
      'index.ts',
      'about.ts',
      'blog/index.ts',
      'blog/[slug].ts',   // dynamic — excluded
      '[...all].ts',      // catch-all — excluded
    ]);

    const prerenderRoutes = extractPrerenderRoutes(routes);

    expect(prerenderRoutes).toContain('/');
    expect(prerenderRoutes).toContain('/about');
    expect(prerenderRoutes).toContain('/blog');
    expect(prerenderRoutes).not.toContain('/blog/:slug');
    expect(prerenderRoutes).not.toContain('/:all(.*)*');
  });

  it('returns an empty array when all pages are dynamic', () => {
    const routes = buildRoutes(['[id].ts', '[...all].ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    expect(prerenderRoutes).toHaveLength(0);
  });

  it('returns all routes when none are dynamic', () => {
    const routes = buildRoutes(['index.ts', 'about.ts', 'contact.ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    expect(prerenderRoutes).toHaveLength(3);
    expect(prerenderRoutes).toContain('/');
    expect(prerenderRoutes).toContain('/about');
    expect(prerenderRoutes).toContain('/contact');
  });

  it('excludes optional param routes (isDynamic === true)', () => {
    const routes = buildRoutes(['[[lang]]/index.ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    // Optional params produce isDynamic: true — excluded from prerender
    expect(prerenderRoutes).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// Route sort order in generated output
// ---------------------------------------------------------------------------

describe('generateManifestModule — sort order', () => {
  it('places static routes before dynamic routes in the generated JSON', () => {
    const routes = buildRoutes([
      '[slug].ts',         // dynamic
      'about.ts',         // static
      'index.ts',         // static
    ]);
    const source = generateManifestModule(routes);

    const indexOfAbout = source.indexOf('"path": "/about"');
    const indexOfSlug = source.indexOf('"path": "/:slug"');

    expect(indexOfAbout).toBeLessThan(indexOfSlug);
  });

  it('places dynamic routes before catch-all routes in the generated JSON', () => {
    const routes = buildRoutes([
      '[...all].ts',      // catch-all
      'blog/[slug].ts',   // dynamic
    ]);
    const source = generateManifestModule(routes);

    const indexOfSlug = source.indexOf('"path": "/blog/:slug"');
    const indexOfCatchAll = source.indexOf('"path": "/:all(.*)*"');

    expect(indexOfSlug).toBeLessThan(indexOfCatchAll);
  });
});
