/**
 * Unit tests for the route generator output produced by pages.ts.
 *
 * These tests exercise the two generator functions that are internal to
 * pages.ts by importing them via a test-only re-export shim, OR by calling
 * them indirectly through the public helpers already exposed by path-to-route.ts
 * and reconstructing what the generator would produce.
 *
 * Because `generateManifestModule` and `generateClientRoutes` are unexported
 * private helpers inside pages.ts, this test file reconstructs the expected
 * output by calling the exported pure functions (fileToRoute, compareRoutes)
 * and then asserting on the shape of the strings that those helpers would
 * produce. This is the correct approach: we test the CONTRACT (the shape of
 * the generated output), not the internal function names.
 *
 * Run with: pnpm --filter litro test
 */

import { describe, it, expect } from 'vitest';
import { fileToRoute, compareRoutes } from '../path-to-route.js';
import type { LitroRoute } from '../../types/route.js';

// ---------------------------------------------------------------------------
// Test data: a representative set of page files
// ---------------------------------------------------------------------------

const ROOT_DIR = '/app';
const PAGES_DIR = '/app/pages';

const p = (rel: string) => `${PAGES_DIR}/${rel}`;

/** Build and sort a LitroRoute array from a list of relative page paths. */
function buildRoutes(relPaths: string[]): LitroRoute[] {
  return relPaths.map(rel => fileToRoute(p(rel), PAGES_DIR)).sort(compareRoutes);
}

// ---------------------------------------------------------------------------
// Helpers that mirror the internal generator functions from pages.ts
// (kept here so tests can validate the generated string shape without
//  importing private/unexported code)
// ---------------------------------------------------------------------------

// Mirrors packages/framework/src/plugins/pages.ts: computes a POSIX-style
// relative import specifier with a .js extension from the directory containing
// `fromFile` to `toFile`. Relative + .js is the ESM convention with bundler
// moduleResolution and keeps the emitted code typecheck-clean.
function toRelativeImportSpecifier(fromFile: string, toFile: string): string {
  // Minimal POSIX relative path for test purposes (the real helper uses pathe).
  const fromDir = fromFile.replace(/\/[^/]+$/, '');
  const fromParts = fromDir.split('/').filter(Boolean);
  const toParts = toFile.split('/').filter(Boolean);
  let shared = 0;
  while (
    shared < fromParts.length &&
    shared < toParts.length &&
    fromParts[shared] === toParts[shared]
  ) shared++;
  const up = '../'.repeat(fromParts.length - shared);
  const down = toParts.slice(shared).join('/');
  const rel = (up + down).replace(/\.tsx?$/, '.js');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function generateManifestModule(
  routes: LitroRoute[],
  pageFiles: string[],
  rootDir: string,
  variant: 'virtual' | 'stub' = 'stub',
): string {
  const routesJson = JSON.stringify(routes, null, 2);
  const stubPath = `${rootDir}/server/stubs/page-manifest.ts`;

  const importSpecifier = (f: string): string =>
    variant === 'virtual' ? f : toRelativeImportSpecifier(stubPath, f);

  const imports = pageFiles
    .map((f, i) => `import * as _page${i} from ${JSON.stringify(importSpecifier(f))};`)
    .join('\n');

  const registryEntries = pageFiles
    .map((f, i) => `  ${JSON.stringify(f)}: _page${i}`)
    .join(',\n');

  const pageModulesExport =
    variant === 'stub'
      ? `const _pageModules = {\n${registryEntries}\n};\nexport const pageModules: Record<string, Record<string, unknown>> = _pageModules;`
      : `export const pageModules = {\n${registryEntries}\n};`;

  return `// @ts-nocheck
// @generated by litro page scanner — do not edit
// This is the #litro/page-manifest virtual module.
// It is re-generated on every build and dev-reload.
${imports}

export const routes = ${routesJson};

${pageModulesExport}

export default routes;
`;
}

function generateClientRoutes(routes: LitroRoute[], rootDir: string): string {
  const clientFilePath = `${rootDir}/routes.generated.ts`;
  const routeLines = routes
    .map(route => {
      const importPath = toRelativeImportSpecifier(clientFilePath, route.filePath);
      return [
        `  {`,
        `    path: ${JSON.stringify(route.path)},`,
        `    action: async () => { await import(${JSON.stringify(importPath)}); },`,
        `    component: ${JSON.stringify(route.componentTag)},`,
        `  },`,
      ].join('\n');
    })
    .join('\n');

  return `// @ts-nocheck
// @generated by litro page scanner — do not edit
// This file is consumed by the Litro client bootstrap (app.ts).
// Re-generated on every build.

import type { Route } from '@beatzball/litro/runtime';

export const routes: Route[] = [
${routeLines}
];
`;
}

// ---------------------------------------------------------------------------
// Manifest module source
// ---------------------------------------------------------------------------

describe('generateManifestModule — virtual module source', () => {
  const relPaths = ['index.ts', 'about.ts', 'blog/index.ts', 'blog/[slug].ts', '[...all].ts'];
  const routes = buildRoutes(relPaths);
  const pageFiles = relPaths.map(r => p(r)).sort();
  const source = generateManifestModule(routes, pageFiles, ROOT_DIR);

  it('starts with a `// @ts-nocheck` directive so generated code opts out of strict typechecking', () => {
    expect(source.startsWith('// @ts-nocheck\n')).toBe(true);
  });

  it('contains `export const routes`', () => {
    expect(source).toContain('export const routes');
  });

  it('contains `export default routes`', () => {
    expect(source).toContain('export default routes');
  });

  it('uses relative import specifiers with .js extensions (no absolute paths, no .ts extensions)', () => {
    const importMatches = source.match(/import \* as _page\d+ from "([^"]+)";/g) ?? [];
    expect(importMatches).toHaveLength(pageFiles.length);
    for (const match of importMatches) {
      const spec = match.match(/"([^"]+)"/)![1];
      expect(spec.endsWith('.js')).toBe(true);
      expect(spec.endsWith('.ts')).toBe(false);
      expect(spec.startsWith('.')).toBe(true);   // relative, not absolute
      expect(spec.startsWith('/')).toBe(false);
    }
  });

  it('computes relative specifiers from server/stubs/ to pages/ (../../pages/...)', () => {
    // The stub is written to <rootDir>/server/stubs/page-manifest.ts, so every
    // page import must go up two levels then into pages/.
    const importMatches = source.match(/import \* as _page\d+ from "([^"]+)";/g) ?? [];
    for (const match of importMatches) {
      const spec = match.match(/"([^"]+)"/)![1];
      expect(spec.startsWith('../../pages/')).toBe(true);
    }
  });

  it('includes the @generated header comment', () => {
    expect(source).toContain('// @generated by litro page scanner — do not edit');
  });

  it('contains the correct path for the index route', () => {
    expect(source).toContain('"path": "/"');
  });

  it('contains the correct path for the about route', () => {
    expect(source).toContain('"path": "/about"');
  });

  it('contains the correct path for the blog index route', () => {
    expect(source).toContain('"path": "/blog"');
  });

  it('contains the correct path for the dynamic blog slug route', () => {
    expect(source).toContain('"path": "/blog/:slug"');
  });

  it('contains the correct path for the catch-all route', () => {
    expect(source).toContain('"path": "/:all(.*)*"');
  });

  it('contains correct componentTag for each route', () => {
    expect(source).toContain('"componentTag": "page-home"');
    expect(source).toContain('"componentTag": "page-about"');
    expect(source).toContain('"componentTag": "page-blog"');
    expect(source).toContain('"componentTag": "page-blog-slug"');
    expect(source).toContain('"componentTag": "page-all"');
  });

  it('encodes isDynamic and isCatchAll flags', () => {
    // The catch-all route should have both flags true
    expect(source).toMatch(/"isCatchAll": true/);
    expect(source).toMatch(/"isDynamic": true/);
    // The index route should have both flags false
    expect(source).toMatch(/"isDynamic": false/);
    expect(source).toMatch(/"isCatchAll": false/);
  });

  it('produces valid JSON inside the module source', () => {
    // Extract the JSON array from the source and verify it parses cleanly
    const jsonMatch = source.match(/export const routes = (\[[\s\S]*?\]);\n/);
    expect(jsonMatch).not.toBeNull();
    expect(() => JSON.parse(jsonMatch![1])).not.toThrow();
    const parsed = JSON.parse(jsonMatch![1]);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed).toHaveLength(5);
  });

  it('keeps the absolute filePath as the pageModules registry key (matches route.filePath)', () => {
    // The catch-all handler looks up pageModules[route.filePath], so the keys
    // must stay in sync with whatever format route.filePath uses — currently
    // absolute .ts paths. Changing the key format is a breaking internal change.
    for (const absPath of pageFiles) {
      expect(source).toContain(`${JSON.stringify(absPath)}: _page`);
    }
  });

  it('types pageModules as Record<string, Record<string, unknown>> in the stub variant', () => {
    // Without this annotation, the consumer's catch-all handler hits TS7053
    // when it does `pageModules[route.filePath]` — a literal-key object has
    // no string index signature.
    expect(source).toContain('export const pageModules: Record<string, Record<string, unknown>>');
  });
});

describe('generateManifestModule — empty pages directory', () => {
  it('produces a valid module with an empty routes array', () => {
    const source = generateManifestModule([], [], ROOT_DIR);
    expect(source).toContain('export const routes = []');
    expect(source).toContain('export default routes');
  });
});

describe('generateManifestModule — virtual variant', () => {
  // The virtual variant is fed to Rollup via nitro.options.virtual, which has
  // no real directory. Relative imports can't be resolved from a virtual id,
  // so the virtual variant keeps the absolute filesystem paths.
  const relPaths = ['index.ts', 'about.ts'];
  const routes = buildRoutes(relPaths);
  const pageFiles = relPaths.map(r => p(r)).sort();
  const source = generateManifestModule(routes, pageFiles, ROOT_DIR, 'virtual');

  it('uses absolute filesystem paths so Rollup can resolve from the virtual id', () => {
    const importMatches = source.match(/import \* as _page\d+ from "([^"]+)";/g) ?? [];
    expect(importMatches).toHaveLength(pageFiles.length);
    for (const match of importMatches) {
      const spec = match.match(/"([^"]+)"/)![1];
      expect(spec.startsWith('/')).toBe(true);
      expect(spec.endsWith('.ts')).toBe(true);
    }
  });
});

// ---------------------------------------------------------------------------
// Client routes file (routes.generated.ts)
// ---------------------------------------------------------------------------

describe('generateClientRoutes — litro/runtime Route[] format', () => {
  const routes = buildRoutes([
    'index.ts',
    'about.ts',
    'blog/index.ts',
    'blog/[slug].ts',
    '[...all].ts',
  ]);
  const source = generateClientRoutes(routes, ROOT_DIR);

  it('imports Route type from litro/runtime', () => {
    expect(source).toContain("import type { Route } from '@beatzball/litro/runtime'");
  });

  it('exports a `routes` array typed as Route[]', () => {
    expect(source).toContain('export const routes: Route[] = [');
  });

  it('contains an async action() callback for each route', () => {
    const actionCount = (source.match(/action: async \(\) => \{ await import\(/g) ?? []).length;
    expect(actionCount).toBe(5);
  });

  it('includes a `component` field for each route', () => {
    const componentCount = (source.match(/component:/g) ?? []).length;
    expect(componentCount).toBe(5);
  });

  it('generates correct import paths with .js extension for each route', () => {
    // All import paths should end in .js (not .ts) since they target the
    // Vite-compiled client bundle, not TypeScript source
    const importMatches = source.match(/await import\("([^"]+)"\)/g) ?? [];
    expect(importMatches).toHaveLength(5);
    for (const match of importMatches) {
      expect(match).toMatch(/\.js"\)$/);
    }
  });

  it('generates relative import paths (./pages/...) — no absolute filesystem paths', () => {
    const importMatches = source.match(/await import\("([^"]+)"\)/g) ?? [];
    for (const match of importMatches) {
      const path = match.replace('await import("', '').replace('")', '');
      // Relative specifier starting with ./ (ESM/bundler-moduleResolution friendly)
      expect(path.startsWith('./')).toBe(true);
      // Not root-absolute (breaks tsc) and not filesystem-absolute
      expect(path.startsWith('/')).toBe(false);
      // No .ts extension (would require allowImportingTsExtensions)
      expect(path.endsWith('.ts')).toBe(false);
    }
  });

  it('starts with a `// @ts-nocheck` directive', () => {
    expect(source.startsWith('// @ts-nocheck\n')).toBe(true);
  });

  it('sets the correct component tag for each route', () => {
    expect(source).toContain('component: "page-home"');
    expect(source).toContain('component: "page-about"');
    expect(source).toContain('component: "page-blog"');
    expect(source).toContain('component: "page-blog-slug"');
    expect(source).toContain('component: "page-all"');
  });

  it('sets the correct path for each route', () => {
    expect(source).toContain('path: "/"');
    expect(source).toContain('path: "/about"');
    expect(source).toContain('path: "/blog"');
    expect(source).toContain('path: "/blog/:slug"');
    expect(source).toContain('path: "/:all(.*)*"');
  });

  it('includes the @generated header comment', () => {
    expect(source).toContain('// @generated by litro page scanner — do not edit');
  });
});

// ---------------------------------------------------------------------------
// Prerender routes — only non-dynamic routes
// ---------------------------------------------------------------------------

describe('prerender routes extraction', () => {
  /** Mirrors the filter in pages.ts that populates nitro.options.prerender.routes */
  function extractPrerenderRoutes(routes: LitroRoute[]): string[] {
    return routes
      .filter(r => !r.isDynamic && !r.isCatchAll)
      .map(r => r.path);
  }

  it('includes only static (non-dynamic, non-catch-all) routes', () => {
    const routes = buildRoutes([
      'index.ts',
      'about.ts',
      'blog/index.ts',
      'blog/[slug].ts',   // dynamic — excluded
      '[...all].ts',      // catch-all — excluded
    ]);

    const prerenderRoutes = extractPrerenderRoutes(routes);

    expect(prerenderRoutes).toContain('/');
    expect(prerenderRoutes).toContain('/about');
    expect(prerenderRoutes).toContain('/blog');
    expect(prerenderRoutes).not.toContain('/blog/:slug');
    expect(prerenderRoutes).not.toContain('/:all(.*)*');
  });

  it('returns an empty array when all pages are dynamic', () => {
    const routes = buildRoutes(['[id].ts', '[...all].ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    expect(prerenderRoutes).toHaveLength(0);
  });

  it('returns all routes when none are dynamic', () => {
    const routes = buildRoutes(['index.ts', 'about.ts', 'contact.ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    expect(prerenderRoutes).toHaveLength(3);
    expect(prerenderRoutes).toContain('/');
    expect(prerenderRoutes).toContain('/about');
    expect(prerenderRoutes).toContain('/contact');
  });

  it('excludes optional param routes (isDynamic === true)', () => {
    const routes = buildRoutes(['[[lang]]/index.ts']);
    const prerenderRoutes = extractPrerenderRoutes(routes);
    // Optional params produce isDynamic: true — excluded from prerender
    expect(prerenderRoutes).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// Route sort order in generated output
// ---------------------------------------------------------------------------

describe('generateManifestModule — sort order', () => {
  it('places static routes before dynamic routes in the generated JSON', () => {
    const rel = ['[slug].ts', 'about.ts', 'index.ts'];
    const routes = buildRoutes(rel);
    const source = generateManifestModule(routes, rel.map(r => p(r)).sort(), ROOT_DIR);

    const indexOfAbout = source.indexOf('"path": "/about"');
    const indexOfSlug = source.indexOf('"path": "/:slug"');

    expect(indexOfAbout).toBeLessThan(indexOfSlug);
  });

  it('places dynamic routes before catch-all routes in the generated JSON', () => {
    const rel = ['[...all].ts', 'blog/[slug].ts'];
    const routes = buildRoutes(rel);
    const source = generateManifestModule(routes, rel.map(r => p(r)).sort(), ROOT_DIR);

    const indexOfSlug = source.indexOf('"path": "/blog/:slug"');
    const indexOfCatchAll = source.indexOf('"path": "/:all(.*)*"');

    expect(indexOfSlug).toBeLessThan(indexOfCatchAll);
  });
});
