/**
 * Elena starlight client entry point.
 *
 * NO HYDRATION SUPPORT SCRIPT NEEDED
 * Elena uses progressive enhancement — components upgrade in place when
 * JavaScript loads. No prototype patching or hydration controller required.
 */

// Client runtime custom elements (router outlet + link)
import '@beatzball/litro/adapter/elena/runtime';

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
if (outlet) {
  outlet.routes = routes;
} else {
  console.warn('[litro] <litro-outlet> not found — router will not start.');
}
