// Elena uses progressive enhancement — no hydration script needed.

// Client runtime: Elena adapter router outlet and link custom elements.
import '@beatzball/litro/adapter/elena/runtime';

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
if (outlet) {
  outlet.routes = routes;
} else {
  console.warn('[litro] <litro-outlet> not found — router will not start.');
}
