/**
 * Catch-all page handler
 *
 * Matches every incoming request that is not an API route or a static asset,
 * finds the corresponding Lit page component from the page manifest, and
 * delegates to createPageHandler() for full SSR streaming.
 *
 * Request flow:
 *   1. Import the page manifest (LitroRoute[]) — generated by the I-2 page
 *      scanner plugin via the #litro/page-manifest virtual module.
 *      Both a named export `routes` and a default export are provided for
 *      import flexibility.
 *   2. Match the request URL path against each entry's `path` pattern.
 *      Routes are pre-sorted: static → dynamic → catch-all, so the first
 *      match in a linear scan is always the most specific.
 *   3. Call createPageHandler({ route }) with the matched LitroRoute and
 *      invoke the returned EventHandler with the current H3 event.
 *   4. If no route matches, return a 404 HTML response.
 *
 * SSR failure mode (handled inside createPageHandler):
 *   If @lit-labs/ssr throws during render, createPageHandler falls back to
 *   a client-only HTML shell so the page remains functional via client-side Lit.
 */

import { defineEventHandler, setResponseHeader, getRequestURL } from 'h3';
import { createPageHandler } from '@beatzball/litro/runtime/create-page-handler.js';
import type { LitroRoute } from '@beatzball/litro';
import { routes, pageModules } from '#litro/page-manifest';

// ---------------------------------------------------------------------------
// Simple route matcher
// ---------------------------------------------------------------------------

/**
 * Matches a URL pathname against the sorted LitroRoute array.
 * Returns the matched route and any extracted URL params.
 *
 * Routes are pre-sorted (static < dynamic < catch-all) by the page scanner,
 * so iterating in order and returning the first match gives highest-specificity
 * wins — exactly what h3's own router does.
 */
function matchRoute(
  pathname: string,
): { route: LitroRoute; params: Record<string, string> } | undefined {
  for (const route of routes) {
    if (route.isCatchAll) {
      // Catch-all matches everything — only reached if no static/dynamic matched
      return { route, params: {} };
    }

    if (!route.isDynamic) {
      // Exact match for static routes
      if (pathname === route.path) {
        return { route, params: {} };
      }
      continue;
    }

    // Dynamic route: convert the h3 path pattern to a named-capture RegExp.
    // Named groups automatically map param names to captured values.
    // Examples:
    //   /blog/:slug        → /^\/blog\/(?<slug>[^/]+)$/
    //   /:lang?            → /^\/(?<lang>[^/]*)?$/
    const regexStr = '^' + route.path
      .replace(/:([^/]+)\(\.\*\)\*/g, '(?<$1>.+)')  // :param(.*)* — catch-all segment
      .replace(/:([^/?]+)\?/g, '(?<$1>[^/]*)?')      // :param? — optional segment
      .replace(/:([^/]+)/g, '(?<$1>[^/]+)')           // :param — required segment
      + '$';

    try {
      const match = pathname.match(new RegExp(regexStr));
      if (match) {
        return { route, params: (match.groups ?? {}) as Record<string, string> };
      }
    } catch {
      // Malformed regex pattern — skip and continue
    }
  }

  return undefined;
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export default defineEventHandler(async (event) => {
  const url = getRequestURL(event);
  const pathname = url.pathname;

  const result = matchRoute(pathname);

  if (!result) {
    setResponseHeader(event, 'content-type', 'text/html; charset=utf-8');
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>404 Not Found — Litro</title>
</head>
<body>
  <h1>404 — Page Not Found</h1>
  <p>No page matched the path <code>${pathname}</code>.</p>
</body>
</html>`;
  }

  const { route: matched, params } = result;

  // Populate event.context.params so pageData fetchers can access route params
  // (e.g., event.context.params.slug for /blog/:slug).
  event.context.params = { ...event.context.params, ...params };

  // Create and immediately invoke the SSR handler for this route.
  // createPageHandler() returns an H3 EventHandler that streams the
  // @lit-labs/ssr output with DSD + hydration shell.
  // pageModules[matched.filePath] provides the pre-bundled module so
  // createPageHandler can access pageData without a runtime .ts import.
  const handler = createPageHandler({
    route: matched,
    pageModule: pageModules[matched.filePath],
  });
  return handler(event);
});
