/**
 * Vite plugin: server-action client stubs.
 *
 * Any module matching *.server.{ts,tsx,js,mjs} that enters the CLIENT module
 * graph is replaced, at transform time, by a generated stub whose every
 * export forwards to callAction('<hashed id>', args). The original code —
 * and therefore all of its imports (DB drivers, secrets) — never enters the
 * client bundle. TypeScript still resolves the import to the real file, so
 * call sites keep the original signatures.
 *
 * Ordering: default (normal) — Vite's core TS transform runs first, so this
 * transform always receives plain JS. Do NOT add `enforce: 'pre'` (it would
 * feed raw TypeScript to es-module-lexer and parseAst).
 *
 * The id filter tests the RESOLVED filename: source imports use `.js`
 * specifiers by repo convention, but Vite resolves them to the `.server.ts`
 * file before transform runs.
 */
import type { Plugin } from 'vite';
import { parseAst } from 'vite';
import { init, parse as parseExports } from 'es-module-lexer';
import { hashActionId, normalizeActionPath } from '../actions/hash.js';

const SERVER_MODULE_RE = /\.server\.(ts|tsx|js|mjs)(\?.*)?$/;

const SERVER_SUBPATH = '@beatzball/litro/actions/server';
const SERVER_SUBPATH_STUB_ID = '\0litro:actions-server-stub';

const SERVER_SUBPATH_STUB = `// @generated by litro:actions — browser stub for a server-only module
const serverOnly = (name) => () => {
  throw new Error('[litro] ' + name + '() is server-only — call it inside definePageData or other server code.');
};
export const csrfToken = serverOnly('csrfToken');
export const getFormErrors = serverOnly('getFormErrors');
export const setFormErrorCookie = serverOnly('setFormErrorCookie');
export const verifyCsrfToken = serverOnly('verifyCsrfToken');
export const stampActionIds = serverOnly('stampActionIds');
export const CSRF_COOKIE = '__Host-litro-csrf';
export const FORM_ERROR_COOKIE = 'litro-form-error';
`;

/** Export initializers that are definitely not functions — exporting one
 *  from a .server.ts module is a build error (every export becomes a public
 *  endpoint; data exports are either a leak or a guaranteed runtime 404). */
const NON_FUNCTION_INIT_TYPES = new Set([
  'Literal',
  'ObjectExpression',
  'ArrayExpression',
  'TemplateLiteral',
  'BinaryExpression',
  'UnaryExpression',
  'UpdateExpression',
]);

function assertNoDataExports(code: string, id: string): void {
  const program = parseAst(code);
  for (const node of program.body as Array<{ type: string; declaration?: unknown }>) {
    if (node.type === 'ExportAllDeclaration') {
      throw new Error(
        `[litro:actions] ${id}: \`export *\` is not supported in .server modules — ` +
          `export names must be statically knowable to generate client stubs.`,
      );
    }
    if (node.type !== 'ExportNamedDeclaration') continue;
    const decl = node.declaration as
      | { type: string; declarations?: Array<{ id: { name?: string }; init?: { type: string } | null }> }
      | null
      | undefined;
    if (!decl || decl.type !== 'VariableDeclaration') continue;
    for (const d of decl.declarations ?? []) {
      if (d.init && NON_FUNCTION_INIT_TYPES.has(d.init.type)) {
        throw new Error(
          `[litro:actions] ${id}: non-function export "${d.id.name ?? '?'}" — every export of a ` +
            `.server module becomes a public endpoint. Keep data/constants unexported or move ` +
            `them to a non-.server module.`,
        );
      }
    }
  }
}

export function litroActionsPlugin(): Plugin {
  let root = process.cwd();

  return {
    name: 'litro:actions',

    configResolved(config) {
      root = config.root;
    },

    resolveId(id) {
      if (id === SERVER_SUBPATH) return SERVER_SUBPATH_STUB_ID;
    },

    load(id) {
      if (id === SERVER_SUBPATH_STUB_ID) return SERVER_SUBPATH_STUB;
    },

    async transform(code, id) {
      if (!SERVER_MODULE_RE.test(id)) return null;
      // Mirror the Nitro scanner's exclusion: third-party *.server.* files in
      // node_modules are never registered server-side, so stubbing them would
      // produce guaranteed-404 ids.
      if (id.includes('/node_modules/')) return null;
      await init;

      assertNoDataExports(code, id);

      const relPath = normalizeActionPath(root, id);
      const [, exports] = parseExports(code);

      const lines: string[] = [
        '// @generated by litro:actions — client stub for a .server module',
        `import { makeStub } from '@beatzball/litro/actions/client';`,
      ];
      for (const e of exports) {
        const name = e.n;
        const actionId = hashActionId(relPath, name);
        lines.push(
          name === 'default'
            ? `export default makeStub(${JSON.stringify(actionId)});`
            : `export const ${name} = makeStub(${JSON.stringify(actionId)});`,
        );
      }

      return { code: lines.join('\n'), map: null };
    },
  };
}
