// @generated by litro content plugin — do not edit
// litro:content stub — resolves to the project's content directory
import { ContentIndex } from '@beatzball/litro/content';

const _index = new ContentIndex("/Users/zaidalbaker/w/beatzball/litro/.claude/worktrees/feat-astro-starlight-recipe/playground-starlight/content");

// Start building eagerly at server startup so the first request is not blocked.
// The promise is cached; getPosts/getPost/getTags/getGlobalData await it if
// the eager build has not yet completed.
const _ready = _index.build().catch((err) => {
  console.error('[litro:content] Failed to build content index:', err);
});

export async function getPosts(options) {
  await _ready;
  return _index.getPosts(options);
}

export async function getPost(slug) {
  await _ready;
  return _index.getPost(slug);
}

export async function getTags() {
  await _ready;
  return _index.getTags();
}

export async function getGlobalData() {
  await _ready;
  return _index.getGlobalData();
}
