/**
 * Playground client entry point.
 *
 * CRITICAL IMPORT ORDER
 * ─────────────────────
 * @lit-labs/ssr-client/lit-element-hydrate-support.js MUST be the very first
 * import in this file — before any Lit code, before any page component imports.
 *
 * This module patches LitElement.prototype.createRenderRoot() so that when a
 * component upgrades on the client it enters "hydration mode" and attaches to
 * the existing Declarative Shadow DOM the server streamed, rather than
 * blowing away the SSR content with a fresh render.
 *
 * If this import appears AFTER any LitElement subclass is evaluated, the patch
 * arrives too late and hydration silently falls back to a full client render,
 * causing a flash of unstyled/re-rendered content.
 */

// Step 1 — MUST BE FIRST: patch LitElement before any Lit code is evaluated.
import '@lit-labs/ssr-client/lit-element-hydrate-support.js';

// Step 2 — client runtime custom elements (router outlet + link)
import 'litro/runtime/LitroOutlet.js';
import 'litro/runtime/LitroLink.js';

// Step 3 — routes generated by I-2's page scanner
// routes.generated.ts lives at the project root (not in dist/) so Vite's
// emptyOutDir does not delete it, and it can be re-generated before vite build.
import { routes } from './routes.generated.js';

// Step 4 — initialize the router when the DOM is ready
// We set .routes on the <litro-outlet> element rather than calling initRouter()
// here so the element's own firstUpdated() lifecycle creates the Router instance
// after the element is in the DOM.
document.addEventListener('DOMContentLoaded', () => {
  const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
  if (outlet) {
    outlet.routes = routes;
  } else {
    console.warn(
      '[litro] DOMContentLoaded: no <litro-outlet> found in the document. ' +
        'Make sure the HTML shell includes <litro-outlet></litro-outlet>.'
    );
  }
});
